apiVersion: v1
kind: Service
metadata:
  name: warehousing-production-service
  namespace: warehousing
  labels:
    app: warehousing-production
    domain: warehousing
spec:
  selector:
    app: warehousing-production
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
