apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: inventory-service-monitor
  namespace: warehousing
  labels:
    app: inventory-service
    domain: warehousing
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: inventory-service
  endpoints:
  - port: metrics
    interval: 30s
    path: /actuator/prometheus
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: warehouse-management-monitor
  namespace: warehousing
  labels:
    app: warehouse-management-service
    domain: warehousing
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: warehouse-management-service
  endpoints:
  - port: metrics
    interval: 30s
    path: /actuator/prometheus
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: warehouse-analytics-monitor
  namespace: warehousing
  labels:
    app: warehouse-analytics
    domain: warehousing
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: warehouse-analytics
  endpoints:
  - port: metrics
    interval: 30s
    path: /actuator/prometheus
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node