apiVersion: apps/v1
kind: Deployment
metadata:
  name: facility-owner-customer-portal
  namespace: warehousing
  labels:
    app: facility-owner-customer-portal
    component: frontend
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: facility-owner-customer-portal
  template:
    metadata:
      labels:
        app: facility-owner-customer-portal
        component: frontend
        version: v1.0.0
    spec:
      containers:
      - name: facility-owner-customer-portal
        image: exalt/facility-owner-customer-portal:latest
        ports:
        - containerPort: 3202
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: VUE_APP_API_BASE_URL
          value: "http://warehouse-management-service:8206"
        - name: VUE_APP_AUTH_URL
          value: "http://auth-service:8080"
        - name: VUE_APP_MARKETPLACE_URL
          value: "http://customer-storage-marketplace-service:8230"
        - name: VUE_APP_BILLING_URL
          value: "http://billing-service:8200"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3202
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3202
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: nginx-cache
          mountPath: /var/cache/nginx
      volumes:
      - name: tmp
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
      securityContext:
        fsGroup: 101
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300