apiVersion: v1
kind: Service
metadata:
  name: facility-owner-customer-portal-service
  namespace: warehousing
  labels:
    app: facility-owner-customer-portal
    component: frontend
spec:
  selector:
    app: facility-owner-customer-portal
  ports:
  - name: http
    port: 3202
    targetPort: 3202
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: facility-owner-customer-portal-loadbalancer
  namespace: warehousing
  labels:
    app: facility-owner-customer-portal
    component: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012"
spec:
  selector:
    app: facility-owner-customer-portal
  ports:
  - name: http
    port: 80
    targetPort: 3202
    protocol: TCP
  - name: https
    port: 443
    targetPort: 3202
    protocol: TCP
  type: LoadBalancer