version: '3.8'

services:
  self-storage-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: self-storage-service_container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - JAVA_OPTS=-Xmx512m -Xms256m
    env_file:
      - .env
    networks:
      - exalt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  exalt-network:
    external: true
