apiVersion: v1
kind: Service
metadata:
  name: regional-admin-service
  namespace: warehousing
  labels:
    app: regional-admin
    domain: warehousing
spec:
  selector:
    app: regional-admin
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
