apiVersion: v1
kind: Service
metadata:
  name: self-storage-service-service
  namespace: warehousing
  labels:
    app: self-storage-service
    domain: warehousing
spec:
  selector:
    app: self-storage-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
