apiVersion: v1
kind: Service
metadata:
  name: integration-tests-service
  namespace: warehousing
  labels:
    app: integration-tests
    domain: warehousing
spec:
  selector:
    app: integration-tests
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
