apiVersion: v1
kind: Service
metadata:
  name: warehousing-staging-service
  namespace: warehousing
  labels:
    app: warehousing-staging
    domain: warehousing
spec:
  selector:
    app: warehousing-staging
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
