# Database secrets for warehousing services
# These should be created using kubectl create secret or a secrets management tool
# Example: kubectl create secret generic inventory-db-secret --from-literal=url=jdbc:postgresql://postgres:5432/inventory_db --from-literal=username=inventory_user --from-literal=password=your_password
---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-db-secret
  labels:
    app: inventory-service
    domain: warehousing
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres-service:5432/inventory_db"
  username: "inventory_user"
  password: "CHANGE_ME_IN_PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: warehouse-db-secret
  labels:
    app: warehouse-management-service
    domain: warehousing
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres-service:5432/warehouse_db"
  username: "warehouse_user"
  password: "CHANGE_ME_IN_PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-db-secret
  labels:
    app: warehouse-analytics
    domain: warehousing
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres-service:5432/analytics_db"
  username: "analytics_user"
  password: "CHANGE_ME_IN_PRODUCTION"