apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
    domain: warehousing
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
        domain: warehousing
        tier: backend
    spec:
      serviceAccountName: inventory-service
      containers:
      - name: inventory-service
        image: exalt/inventory-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
          name: http
          protocol: TCP
        - containerPort: 8090
          name: metrics
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SERVER_PORT
          value: "8082"
        - name: MANAGEMENT_SERVER_PORT
          value: "8090"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: inventory-db-secret
              key: url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: inventory-db-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-db-secret
              key: password
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-cluster-kafka-bootstrap:9092"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://service-registry:8761/eureka/"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: metrics
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: logs
          mountPath: /var/log/inventory-service
      volumes:
      - name: config
        configMap:
          name: inventory-service-config
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-service
    domain: warehousing
spec:
  type: ClusterIP
  selector:
    app: inventory-service
  ports:
  - name: http
    port: 8082
    targetPort: 8082
    protocol: TCP
  - name: metrics
    port: 8090
    targetPort: 8090
    protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service
  labels:
    app: inventory-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  labels:
    app: inventory-service
data:
  application.yml: |
    spring:
      application:
        name: inventory-service
      cloud:
        kubernetes:
          reload:
            enabled: true
            mode: event
            strategy: refresh
      jpa:
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
      kafka:
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
          group-id: inventory-service
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          properties:
            spring.json.trusted.packages: "*"
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      metrics:
        export:
          prometheus:
            enabled: true
        tags:
          application: ${spring.application.name}
    
    logging:
      level:
        com.exalt.warehousing.inventory: DEBUG
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"