apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: warehousing

commonLabels:
  ecosystem: social-ecommerce
  domain: warehousing
  managed-by: kustomize

resources:
  - inventory-service-deployment.yaml
  - warehouse-management-deployment.yaml
  - warehouse-analytics-deployment.yaml
  - database-secrets.yaml
  - hpa.yaml
  - network-policies.yaml

images:
  - name: exalt/inventory-service
    newTag: latest
  - name: exalt/warehouse-management-service
    newTag: latest
  - name: exalt/warehouse-analytics
    newTag: latest

replicas:
  - name: inventory-service
    count: 3
  - name: warehouse-management-service
    count: 2
  - name: warehouse-analytics
    count: 2

configMapGenerator:
  - name: warehousing-common-config
    literals:
      - EUREKA_SERVER_URL=http://service-registry:8761/eureka/
      - KAFKA_BOOTSTRAP_SERVERS=kafka-cluster-kafka-bootstrap:9092
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SPRING_PROFILES_ACTIVE=kubernetes

secretGenerator:
  - name: warehousing-common-secret
    type: Opaque
    literals:
      - ENCRYPT_KEY=warehousing-encrypt-key-changeme