version: '3.8'

services:
  # Simplified staging environment
  postgres-staging:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: warehousing_staging
      POSTGRES_USER: staging_user
      POSTGRES_PASSWORD: staging_pass
    ports:
      - "5433:5432"
    volumes:
      - staging_postgres_data:/var/lib/postgresql/data

  redis-staging:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  # All services in single compose for staging
  warehousing-main:
    build: ../
    environment:
      SPRING_PROFILES_ACTIVE: staging
      DB_HOST: postgres-staging
    ports:
      - "8080:8080"
    depends_on:
      - postgres-staging
      - redis-staging

  billing-service:
    build: ../billing-service
    environment:
      SPRING_PROFILES_ACTIVE: staging
    ports:
      - "8083:8083"

  inventory-service:
    build: ../inventory-service
    environment:
      SPRING_PROFILES_ACTIVE: staging
    ports:
      - "8084:8084"

volumes:
  staging_postgres_data:
