apiVersion: v1
kind: Service
metadata:
  name: staff-mobile-app-service
  namespace: warehousing
  labels:
    app: staff-mobile-app
    domain: warehousing
spec:
  selector:
    app: staff-mobile-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
