apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: warehousing-prod

commonLabels:
  environment: production

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patches.yaml
  - hpa-patches.yaml

configMapGenerator:
  - name: production-config
    behavior: merge
    literals:
      - LOG_LEVEL=INFO
      - SPRING_PROFILES_ACTIVE=kubernetes,production
      - METRICS_ENABLED=true
      - TRACING_ENABLED=true

secretGenerator:
  - name: production-secrets
    behavior: merge
    files:
      - tls.crt=tls/cert.pem
      - tls.key=tls/key.pem

replicas:
  - name: inventory-service
    count: 5
  - name: warehouse-management-service
    count: 3
  - name: warehouse-analytics
    count: 3

images:
  - name: exalt/inventory-service
    newTag: 1.0.0
  - name: exalt/warehouse-management-service
    newTag: 1.0.0
  - name: exalt/warehouse-analytics
    newTag: 1.0.0