name: CI - Node.js Services

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'global-hq-admin/**'
      - 'regional-admin/**'
      - 'staff-mobile-app/**'
      - '.github/workflows/ci-nodejs-services.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'global-hq-admin/**'
      - 'regional-admin/**'
      - 'staff-mobile-app/**'
      - '.github/workflows/ci-nodejs-services.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - global-hq-admin
          - regional-admin
          - staff-mobile-app
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ matrix.service }}/package-lock.json
    
    - name: Install dependencies
      run: |
        cd ${{ matrix.service }}
        npm ci
    
    - name: Run linter
      run: |
        cd ${{ matrix.service }}
        npm run lint
    
    - name: Run tests
      run: |
        cd ${{ matrix.service }}
        npm test -- --coverage --watchAll=false
      env:
        CI: true
    
    - name: Build application
      run: |
        cd ${{ matrix.service }}
        npm run build
    
    - name: Upload test coverage
      uses: actions/upload-artifact@v4
      if: matrix.node-version == '20.x'
      with:
        name: coverage-${{ matrix.service }}
        path: ${{ matrix.service }}/coverage/
        retention-days: 7
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: matrix.node-version == '20.x'
      with:
        name: build-${{ matrix.service }}
        path: |
          ${{ matrix.service }}/build/
          ${{ matrix.service }}/dist/
        retention-days: 7

  security-scan:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - global-hq-admin
          - regional-admin
          - staff-mobile-app
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run npm audit
      run: |
        cd ${{ matrix.service }}
        npm audit --production
    
    - name: Run Snyk security scan
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --project-path=${{ matrix.service }}